---
title: "p8105_hw2_tb2715"
author: "Tess"
date: "9/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load libraries
```{r}
library(tidyverse)
library(readxl)
```

##Read in dataset
```{r}
#cpi_data = read_csv(file = "./data/fivethirtyeight_datasets/cpi.csv")

#gdp_data = read_csv(file = "./data/fivethirtyeight_datasets/GDP.csv")

#recession_data = read_csv(file = "./data/fivethirtyeight_datasets/recessions.csv")

```

##Clean trash wheel data
```{r}
#UPDATE WITH NEW DATASET INCLUDE 2019
trash_wheel = read_excel(path = "./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
                         sheet = "Mr. Trash Wheel",
                         col_names = TRUE)

trash_wheel_2019 = read_excel(path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
                         sheet = "Mr. Trash Wheel",
                         col_names = TRUE)

tidy_trash_wheel =
  janitor::clean_names(trash_wheel_2019) %>%
  drop_na(dumpster) %>%
  select(-x15, -x16, -x17) %>%
  mutate(sports_balls = as.integer(sports_balls)) 

precipitation_18 = read_excel(path = "./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
  sheet = "2018 Precipitation", 
  skip = 1,
  col_names = TRUE) %>%
  drop_na(Month) %>%
  mutate(Year = "2018")


precipitation_17 = read_excel(path = "./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
  sheet = "2017 Precipitation", 
  skip = 1,
  col_names = TRUE) %>%
  drop_na(Month) %>%
  mutate(Year = "2017")

precipitation_data = 
  merge(precipitation_18, precipitation_17, by = "Month") %>%
  mutate(Month = as.character(Month))
#HOW TO USE MONTH.NAME

#OR
precipitation_data_test = 
  bind_rows(precipitation_18, precipitation_17) %>%
  mutate(Year = as.numeric(Year)) %>%
  arrange(Month)
```

##Problem 2
```{r}
#upload and clean pols_data
pols_data = read_csv(file = "./data/fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>% 
  separate(col = mon, into = c("year", "month", "day")) %>%
  mutate(
    month = recode(month, "01" = "January", 
                   "02" = "February", 
                   "03" = "March", 
                   "04" = "April", 
                   "05" = "May", 
                   "06" = "June", 
                   "07" = "July", 
                   "08" = "August", 
                   "09" = "September", 
                   "10" = "October", 
                   "11" = "November", 
                   "12" = "December")) %>%
  mutate(president = recode(prez_dem, `1` = "dem", `0` = "gop"))
      
pols_data_tidy = 
  select(pols_data, -prez_gop, -prez_dem, -day)

#upload and clean snp_data
snp_data = read_csv(file = "./data/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>% 
  separate(col = date, into = c("month", "day", "year")) %>%
  mutate(
    month = recode(month, "1" = "January", 
                   "2" = "February", 
                   "3" = "March", 
                   "4" = "April", 
                   "5" = "May", 
                   "6" = "June", 
                   "7" = "July", 
                   "8" = "August", 
                   "9" = "September", 
                   "10" = "October", 
                   "11" = "November", 
                   "12" = "December")) 

snp_data_tidy =
  snp_data[c("year", "month", "close")]

#snp_data_tidy =
  #snp_data %>%
  #distinct(year, month, close) #this works because there are no duplicates but how to arrange columns otherwise?
      
#upload and clean unemployment_data
unemployment_data = read_csv(file = "./data/fivethirtyeight_datasets/unemployment.csv") %>%
  janitor::clean_names() 

tidy_unemployment_data =
    pivot_longer(
    unemployment_data, 
    jan:dec, 
    names_to = "month", 
    values_to = "unemployed") %>%
  mutate(
    month = recode(month, "jan" = "January", 
                   "feb" = "February", 
                   "mar" = "March", 
                   "apr" = "April", 
                   "may" = "May", 
                   "jun" = "June", 
                   "jul" = "July", 
                   "aug" = "August", 
                   "sep" = "September", 
                   "oct" = "October", 
                   "nov" = "November", 
                   "dec" = "December")) 

#merge data sets
merge1 = 
  merge(snp_data_tidy, pols_data_tidy, by = c("year","month"))

merge2 = 
  merge(merge1, tidy_unemployment_data, by = c("year","month"))
  
```

WRITE A PARAGRAPH

##Problem 3
```{r}
baby_name = read_csv(file = "./data/Popular_Baby_Names.csv") %>%
  janitor::clean_names() %>%
  distinct(childs_first_name, ethnicity, year_of_birth, count, rank, gender) 

tidy_baby_name = 
  select(baby_name, -count) 

tidy_baby_name = 
  pivot_wider(
    tidy_baby_name,
    names_from = "year_of_birth", 
    values_from = "rank") 

olivia_baby =
  filter(tidy_baby_name, childs_first_name == "Olivia") 

male_baby = 
  filter(tidy_baby_name, gender == "MALE")

male_plot_df = 
  filter(baby_name, 
         gender == "MALE", 
         ethnicity == "WHITE NON HISPANIC", 
         year_of_birth == "2016")
  
male_plot = 
  ggplot(male_plot_df, aes(x = count, y = rank)) +
  geom_point()

male_plot

  
```

 aggregate(olivia_baby[c("2016", "2015", "2014", "2013", "2012", "2011")], by = list(olivia_baby$childs_first_name, olivia_baby$ethnicity, olivia_baby$gender), FUN = "mean", na.rm = T)